services:
  php:
    build:
      context: ./php-ws
      dockerfile: ./Dockerfile
    container_name: php-echo-server
    ports:
      - "8080:8080"

  golang:
    build:
      context: ./go-ws
      dockerfile: ./Dockerfile
    container_name: golang-echo-server
    ports:
      - "8081:8080"

  node:
    build:
      context: ./node-ws
      dockerfile: ./Dockerfile
    container_name: node-echo-server
    ports:
      - "8082:8080"
